### ISSUE TITLE
immuconf breaks compilation of deps.edn uberjar from uberdeps

### ISSUE THREAD

**Issue by Quezion** [levand/immuconf#10]
### Update after opening this issue

I've realized after filing that this bug is actually for @russelwhitaker's port at #6 -- but there's no way to file issues at that repo. https://github.com/russellwhitaker/immuconf

**As a result, I'm closing this issue, as we can only the forked version's author via comments on #6**

For my own immediate fix, I'll fork clj-uap and have it use plain levand/immuconf from this repo, as that solves the library's issues with the lightest touch.

-----

### Fulltext

Example repo at https://github.com/Quezion/example.immuconf-depsedn , just clone & run `clojure -M:uberjar`

I note that deps.edn uberjar does static analysis using `tools.deps.alpha`... perhaps this is conflicting with the way the reader literals are being defined?

This was initially discovered via usage of https://github.com/ua-parser/uap-clj , but filing here as it's likely due to immuconf. A local fork of uap-clj without immuconf compiles without any issues.

#### Notes from example repo README

The `uberjar` command is supplied by the [uberdeps library](https://github.com/tonsky/uberdeps)

```bash
> clojure -M:uberjar

+ uap-clj/uap-clj #:mvn{:version "1.3.7"}
.   clj-commons/clj-yaml #:mvn{:version "0.7.0"}
.     org.flatland/ordered #:mvn{:version "1.5.7"}
.       org.flatland/useful #:mvn{:version "0.11.6"}
.         org.clojure/tools.macro #:mvn{:version "0.1.1"}
.     org.yaml/snakeyaml #:mvn{:version "1.24"}
.   russellwhitaker/immuconf #:mvn{:version "0.3.1"}
Execution error at uberdeps.api/fn (api.clj:108).
No dispatch macro for: ?
```

After some digging into uberdeps /src/, see -- https://github.com/tonsky/uberdeps/blob/master/src/uberdeps/api.clj#L115

```clj
(def default-mergers
  {"META-INF/plexus/components.xml" components-merger
   #"META-INF/services/.*"          services-merger
   #"data_readers.clj[cs]?"         clojure-maps-merger})
```

I believe the data_readers file is causing this issue. https://github.com/russellwhitaker/immuconf/blob/master/src/data_readers.cljc

``` clj
#?(:cljs (ns immuconf.data-readers
           (:require [immuconf.config]
                     [cljs.reader :as reader])))
#?(:clj {immuconf/override immuconf.config/->Override
         immuconf/default immuconf.config/->Default})
```

Not sure of exact cause. There's some magic going on in `immuconf.config` with an `ns-unmap`

**Comment by Quezion** [comment]
This could arguably be an uberdeps bug. I'm willing to double-file there if we want but I don't have a lot of insight into what's triggering this error.

**Comment by russellwhitaker** [comment]
@Quezion hey man! Great to see you here. I didn't know about the issue of not being able to open Issues on any of my old work. Tell me what you need, and I'll see what I can do.

**Comment by russellwhitaker** [comment]
@Quezion re: "For my own immediate fix, I'll fork clj-uap and have it use plain levand/immuconf from this repo, as that solves the library's issues with the lightest touch." -- if you want to fork-and-pull against my own fork, let me know.

**Comment by Quezion** [comment]
@russellwhitaker Appreciate it, & for anyone looking for the continuation of this thread -- see https://github.com/ua-parser/uap-clj/pull/3

(Thanks to @levand for tolerating the chatter 🙏 )
